# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wgtun < Formula
  desc "WireGuard orchestrator: TUI + launchd daemon for wireguard-go"
  homepage "https://github.com/dncore/wgtun"
  version "0.3.0"
  license "MIT"

  depends_on "wireguard-go"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/dncore/wgtun/releases/download/v0.3.0/wgtun_0.3.0_darwin_amd64.zip"
    sha256 "c5cedf2331d32d7be5b335be8f594e54def58f92419b624f8f16cfe127cd474d"

    def install
      bin.install "wgtun"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/dncore/wgtun/releases/download/v0.3.0/wgtun_0.3.0_darwin_arm64.zip"
    sha256 "ce70af51044cf9d9b73a3457ef08a894d04046bcf03d85121b14e0cb47be67e7"

    def install
      bin.install "wgtun"
    end
  end

  def caveats
    <<~EOS
      Start the daemon (requires root for the launchd LaunchDaemon):

        sudo brew services start wgtun

      Or install the plist directly:

        sudo wgtun daemon --install

      Then open the TUI with `wgtun`.
    EOS
  end

  service do
    run [opt_bin/"wgtun", "daemon"]
    keep_alive true
    working_dir HOMEBREW_PREFIX
    log_path "/var/log/wgtun/daemon.out.log"
    error_log_path "/var/log/wgtun/daemon.err.log"
  end
end
