# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wgtun < Formula
  desc "WireGuard orchestrator: TUI + launchd daemon for wireguard-go"
  homepage "https://github.com/dncore/wgtun"
  version "0.3.3"
  license "MIT"

  depends_on "wireguard-go"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/dncore/wgtun/releases/download/v0.3.3/wgtun_0.3.3_darwin_amd64.zip"
    sha256 "cddc276b56ba069f75910b5628bc3e8306871adf7c2c8cdeaff2e2eccd140eb8"

    def install
      bin.install "wgtun"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/dncore/wgtun/releases/download/v0.3.3/wgtun_0.3.3_darwin_arm64.zip"
    sha256 "61ae3d603d596af1c3f30ab96e9a2d7da54b938ffef115774aad1c87a07c46e2"

    def install
      bin.install "wgtun"
    end
  end

  def caveats
    <<~EOS
      Start the daemon (requires root for the launchd LaunchDaemon):

        sudo brew services start wgtun

      Or install the plist directly:

        sudo wgtun daemon --install

      Then open the TUI with `wgtun`.
    EOS
  end

  service do
    run [opt_bin/"wgtun", "daemon"]
    keep_alive true
    working_dir HOMEBREW_PREFIX
    log_path "/var/log/wgtun/daemon.out.log"
    error_log_path "/var/log/wgtun/daemon.err.log"
  end
end
