# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wgtun < Formula
  desc "WireGuard orchestrator: TUI + launchd daemon for wireguard-go"
  homepage "https://github.com/dncore/wgtun"
  version "0.3.4"
  license "MIT"

  depends_on "wireguard-go"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/dncore/wgtun/releases/download/v0.3.4/wgtun_0.3.4_darwin_amd64.zip"
    sha256 "9f8b8231bc6e53e3d6b9723c4cf60850295fc0859fab0a4ab42efc96f1330ca1"

    def install
      bin.install "wgtun"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/dncore/wgtun/releases/download/v0.3.4/wgtun_0.3.4_darwin_arm64.zip"
    sha256 "0e3c83635a2f0c684b0c43c24e150dae24e639a9676560bde91e97aa8abca4d8"

    def install
      bin.install "wgtun"
    end
  end

  def caveats
    <<~EOS
      Start the daemon (requires root for the launchd LaunchDaemon):

        sudo brew services start wgtun

      Or install the plist directly:

        sudo wgtun daemon --install

      Then open the TUI with `wgtun`.
    EOS
  end

  service do
    run [opt_bin/"wgtun", "daemon"]
    keep_alive true
    working_dir HOMEBREW_PREFIX
    log_path "/var/log/wgtun/daemon.out.log"
    error_log_path "/var/log/wgtun/daemon.err.log"
  end
end
